textos_home_page = {
        "home_ticker": "Bienvenido a Claro video. Da clic aquí para conocer más planes y acceder a canales Premium.",
        "home_ticker_close": "",
        "home_logocv": "",
        "home_input_buscador": "",
        "home_lupa": "",
        "home_avatar": "",
        "home_nodo_inicio": "Inicio",
    # Se agrega Claro Sports
        "home_nodo_CS": "",
        "home_nodo_catalogo": "Catálogo",
        "home_nodo_generos": "Géneros",
        "home_nodo_compra": "Compra y Renta",
        "home_nodo_canales": "Canales",
        "home_nodo_kids": "",
        "home_nodo_miscontenidos": "Mis Contenidos",
        "home_nodo_musica": "",

       # "home_superdestacados": "RENTAR\nCOMPRAR",
        "home_superdestacados": "",


        "home_recomienda": "Claro video te recomienda",
        "home_carrusel_recomienda": "Claro video te recomienda",

        "home_paramount": "",
        "home_carrusel_paramount": "Paramount+ incluido en Claro video",


        "home_coleccion": "Colección Claro video",
        # "home_scroll_left_coleccion": "",
        # "home_scroll_rigth_coleccion": "",

        # Se cambia ver ahora por "Continua viendo"
        "home_carrrusel_Cviendo": "Continúa viendo",

        # "home_familia": "Diversión en Familia",
        # "home_carrusel_familia": "",
        # "home_scroll_left_familia": "",
        # "home_scroll_rigth_familia": "",

        "home_compra": "Top de Compra y Renta",
        "home_carrusel_compra": "",
        # "home_scroll_left_compra": "",
        # "home_scroll_rigth_compra": "",

        # "home_maraton": "Maratón de Series",
        # "home_carrusel_maraton": "",
        # "home_scroll_left_maraton": "",
        # "home_scroll_rigth_maraton": "",

        "home_nuevoen": "Lo Nuevo en Claro video",
        "home_carrusel_nuevoen": "",
        # "home_scroll_left_nuevoen": "",
        # "home_scroll_rigth_nuevoen": "",

        "home_parati": "Para ti",
        "home_carrusel_parati": "",
        # "home_scroll_left_parati": "",
        # "home_scroll_rigth_parati": "",

    #Se añade mi lista
        "home_milista": "Mi lista",
        "home_carrusel_milista": "",
        # "home_scroll_left_milista": "",
        # "home_scroll_rigth_milista": "",

        "home_lomasvisto": "Lo más visto",
        "home_carrusel_lomasvisto": "",
        # "home_scroll_left_lomasvisto": "",
        # "home_scroll_rigth_lomasvisto": "",

        # "home_series": "Las mejores series",
        # "home_carrusel_series": "",
        # "home_scroll_left_series": "",
        # "home_scroll_rigth_series": "",

        # "home_peliculas": "Las mejores películas",
        # "home_carrusel_peliculas": "",
        # "home_scroll_left_peliculas": "",
        # "home_scroll_rigth_peliculas": "",

        # "home_Cn_Oro": "Cine de Oro",
        # "home_carrusel_Cn_Oro": "",
        # "home_scroll_left_Cn_Oro": "",
        # "home_scroll_rigth_Cn_Oro": "",

        "home_hbo": "HBO",
        "home_carrusel_hbo": "",
        # "home_scroll_left_hbo": "",
        # "home_scroll_rigth_hbo": "",

        "home_edye": "Edye",
        "home_carrusel_edye": "",
        # "home_scroll_left_edye": "",
        # "home_scroll_rigth_edye": "",

        "home_noggin": "Noggin",
        "home_carrusel_noggin": "",
        # "home_scroll_left_noggin": "",
        # "home_scroll_rigth_noggin": "",

        "home_atres": "ATRESplayer",
        "home_carrusel_atres": "",
        # "home_scroll_left_atres": "",
        # "home_scroll_rigth_atres": "",

        "home_picardia": "Picardía Nacional",
        "home_carrusel_picardia": "",
        # "home_scroll_left_picardia": "",
        # "home_scroll_rigth_picardia": "",

        "home_rtve": "rtveplay+",
        "home_carrusel_rtve": "",
        # "home_scroll_left_rtve": "",
        # "home_scroll_rigth_rtve": "",

        "home_starzplay": "LIONSGATE+",
        "home_carrusel_starzplay": "",
        # "home_scroll_left_starzplay": "",
        # "home_scroll_rigth_starzplay": "",

        "home_MGM": "MGM",
        "home_carrusel_MGM": "",
        # "home_scroll_left_MGM": "",
        # "home_scroll_rigth_MGM": "",

        "home_karaoke": "Stingray Karaoke",
        "home_carrusel_karaoke": "",
        # "home_scroll_left_karaoke": "",
        # "home_scroll_rigth_karaoke": "",

        "home_qello": "Qello Concerts",
        "home_carrusel_qello": "",


        "catalogo_footer": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
        "catalogo_footer1": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
        "catalogo_footer2": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
        "catalogo_footer3": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
        "catalogo_footer4": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
        "catalogo_footer5": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
        "catalogo_footer6": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",

        # "home_musica": "Música y Conciertos",
        # "home_carrusel_musica": "",
        # "home_scroll_left_musica": "",
        # "home_scroll_rigth_musica": "",
        # #"home_footer": "",
        # #"home_chat": "Chat Ayuda en Línea",
        # #"home_tutoenvideo": "Tutoriales en video",
        # #"home_tutoriales": "Tutoriales",
        # #"home_preguntasfrecuentes": "Preguntas Frecuentes",
        # #"home_requerimientos": "Requerimientos Mínimos",
        # #"home_terminos": "Términos y Condiciones",
        # #"home_politicas": "Políticas de Privacidad",
        # #"home_promociones": "Términos de Promociones",
        # #"home_licencia": "Licencia Usuario Final",
        # #"home_logo_twitter": "",
        # #"home_logo_fb": "",
        # #"home_logo_google": "",
        # #"home_logo_youtube": "",

}

textos_nodo_catalogo_page = {
    "catalogo_subnodo_paramount": "Paramount+",
    "catalogo_subnodo_peliculas": "Películas",
    "catalogo_subnodo_series": "Series",
    "catalogo_subnodo_musica": "Música",
    "catalogo_subnodo_deportes": "Deportes",
    "catalogo_subnodo_documentales": "Documentales",
    "catalogo_subnodo_latinoamericanas": "Latinoamérica",
    "catalogo_subnodo_karaoke": "Karaoke",
    "catalogo_carrsuel_destacados": "",
    "catalogo_MGM": "MGM PRUEBA",
    "catalogo_carrsuel_MGM": "",
    "catalogo_recomienda": "Claro video te recomienda",
    "catalogo_carrsuel_recomienda": "",
    "catalogo_series": "Series de TV",
    "catalogo_carrsuel_series": "",
    "catalogo_accion": "Películas de Acción",
    "catalogo_carrusel_accion": "",
    "catalogo_comedia": "Películas de Comedia",
    "catalogo_carrusel_comedia": "",
    "catalogo_niños": "Niños",
    "catalogo_carrusel_niños": "",
    "catalogo_terror": "Películas de Terror",
    "catalogo_carrusel_terror": "",
    "catalogo_romanticas": "Películas Románticas",
    "catalogo_carrusel_romanticas": "",
    "catalogo_drama": "Películas de Drama",
    "catalogo_carrusel_drama": "",
    "catalogo_documentales": "Documentales",
    "catalogo_carrusel_documentales": "",
    "catalogo_conciertos": "Conciertos",
    "catalogo_carrusel_conciertos": "",
    "catalogo_lomasvisto": "Lo más visto",
    "catalogo_carrusel_lomasvisto": "",
}

textos_nodo_catalogo_paramount_page = {
    "catalogo_paramount_logo": "",
    "catalogo_paramount_bannerseries": "",
    "catalogo_paramount_bannerpaliculas": "",
    "catalogo_paramount_destacados": "",
    "catalogo_footer": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
    "catalogo_paramount_originales": "Paramount + Originales y Exclusivos",
    "catalogo_paramount_carrusel_originales": "",
    "catalogo_paramount_peliculas": "Películas",
    "catalogo_paramount_carrusel_peliculas": "",
    "catalogo_paramount_imperdibles": "Series Imperdibles",
    "catalogo_paramount_carrusel_imperdibles": "",
    "catalogo_paramount_inolvidables": "Series Inolvidables",
    "catalogo_paramount_carrusel_inolvidables": "",
    "catalogo_paramount_garantizadas": "Diversión Garantizada",
    "catalogo_paramount_carrusel_garantizadas": "",
    "catalogo_paramount_niños": "Para los más chiquitos",
    "catalogo_paramount_carrusel_niños": "",
    "catalogo_paramount_reality": "Reality Shows",
    "catalogo_paramount_carrusel_reality": "",
    "catalogo_paramount_comedia": "Series de Comedia",
    "catalogo_paramount_carrusel_comedia": "",
    "catalogo_paramount_lomasvisto": "Lo más visto",
    "catalogo_paramount_carrusel_lomasvisto": "",

}

textos_nodo_catalogo_peliculas_page = {
    "catalogo_peliculas_destacados": "",
    "catalogo_peliculas_terecomienda": "Claro video te recomienda",
    "catalogo_peliculas_carrusel_terecomienda": "",
    "catalogo_peliculas_mexicanas": "Mexicanas",
    "catalogo_perliculas__mexicanas": "",
    "catalogo_perliculas_accion": "Acción y Aventura",
    "catalogo_peliculas_carrusel_accion": "",
    "catalogo_peliculas_ficcion": "Ciencia Ficción y Fantasía",
    "catalogo_peliculas_carrusel_ficcion": "",
    "catalogo_peliculas_cine": "Cine de Oro",
    "catalogo_peliculas_carrusel_cine": "",
    "catalogo_peliculas_clasicas": "Clásicas",
    "catalogo_peliculas_carrusel_clasicas": "",
    "catalogo_peliculas_comedia": "Comedia",
    "catalogo_peliculas_carrusel_comedia": "",
    "catalogo_peliculas_deportes": "Deportes",
    "catalogo_peliculas_carrusel_deportes": "",
    "catalogo_peliculas_animados": "Dibujos Animados",
    "catalogo_peliculas_carrusel_animados": "",
    "catalogo_peliculas_drama": "Drama",
    "catalogo_peliculas_carrusel_drama": "",
    "catalogo_peliculas_familiares": "Familiares",
    "catalogo_peliculas_carrusel_familiares": "",
    "catalogo_peliculas_historicas": "Históricas",
    "catalogo_peliculas_carrusel_historicas": "",
    "catalogo_peliculas_infantiles": "Infantiles",
    "catalogo_peliculas_carrusel_infantiles": "",
    "catalogo_peliculas_internacional": "Internacional",
    "catalogo_peliculas_carrusel_internacional": "",
    "catalogo_peliculas_musicales": "Musicales",
    "catalogo_peliculas_carrusel_musicales": "",
    "catalogo_peliculas_epoca": "Películas de Época",
    "catalogo_peliculas_carrusel_epoca": "",
    "catalogo_peliculas_romanticas": "Románticas",
    "catalogo_peliculas_carrusel_romanticas": "",
    "catalogo_peliculas_suspenso": "Suspenso",
    "catalogo_pelicula_carrusel_suspensp": "",
    "catalogo_peliculas_terror": "Terror",
    "catalogo_peliculas_carrusel_terror": "",
    "catalogo_peliculas_lomasvisto": "Lo más visto",
    "catalogo_peliculas_carrusel_lomasvisto": "",

}

textos_nodo_catalogo_series_page = {
    "catalogo_series_destacados": "",
    "catalogo_series_recomienda": "Claro video te recomienda",
    "catalogo_series_carrusel_recomienda": "",
    "catalogo_series_maraton": "Maratón de Series",
    "catalogo_series_carrusel_maraton": "",
    "catalogo_series_soloencv": "Sólo en Claro video",
    "catalogo_series_carrusel_soloencv": "VER AHORA",
    "catalogo_footer": "Chat Ayuda en Línea\nTutoriales en videoTutorialesPreguntas FrecuentesRequerimientos Mínimos\nTérminos y CondicionesPolíticas de PrivacidadTérminos de PromocionesLicencia Usuario Final",
    "catalogo_series_mexicanas": "Mexicanas",
    "catalogo_series_carrusel_mexicanas": "",
    "catalogo_series_accion": "Acción y Aventura",
    "catalogo_series_carrusel_accion": "",
    "catalogo_series_anime": "Animé y Videojuegos",
    "catalogo_series_carrusel_anime": "",
    "catalogo_series_biograficas": "Biográficas",
    "catalogo_series_carrusel_biograficas": "",
    "catalogo_series_ficcion": "Ciencia Ficción",
    "catalogo_series_carrusel_ficcion": "",
    "catalogo_series_clasicas": "Clásicas",
    "catalogo_series_carrusel_clasicas": "",
    "catalogo_series_comicas": "Cómicas",
    "catalogo_series_carrusel_comicas": "",
    "catalogo_series_dramas": "Dramas",
    "catalogo_series_carrusel_dramas": "",
    "catalogo_series_españolas": "Españolas",
    "catalogo_series_carrusel_españolas": "",
    "catalogo_series_familiares": "Familiares",
    "catalogo_series_carrusel_familiares": "",
    "catalogo_series_historicas": "Históricas",
    "catalogo_series_carrusel_historicas": "",
    "catalogo_series_infantiles": "Infantiles",
    "catalogo_series_carrusel_infantiles": "",
    "catalogo_series_internacionesles": "Internacionales",
    "catalogo_series_carrusel_internacionales": "",
    "catalogo_series_latinoamericanas": "Latinoamericanas",
    "catalogo_series_carrusel_latinoamericanas": "",
    "catalogo_series_policiacas": "Policíacas",
    "catalogo_series_carrusel_policiacas": "",
    "catalogo_series_tv": "Programas de TV",
    "catalogo_series_carrusel_tv": "",
    "catalogo_series_documentales": "Series Documentales",
    "catalogo_series_carrusel_documentales": "",
    "catalogo_series_romanticas": "Románticas",
    "catalogo_series_carrusel_romanticas": "",
    "catalogo_series_suspenso": "Suspenso y Terror",
    "catalogo_series_carrusel_suspenso": "",
    "catalogo_series_lomasvisto": "Lo más visto",
    "catalogo_series_carrusel_lomasvisto": "",
}


